// Map of sign labels to their video assets
export const signsMapping: { [key: string]: any } = {
  '1': require('../assets/videos/1.mp4'),
  '2': require('../assets/videos/2.mp4'),
  '3': require('../assets/videos/3.mp4'),
  '4': require('../assets/videos/4.mp4'),
  '5': require('../assets/videos/5.mp4'),
  '6': require('../assets/videos/6.mp4'),
  '7': require('../assets/videos/7.mp4'),
  '8': require('../assets/videos/8.mp4'),
  '9': require('../assets/videos/9.mp4'),
  '10': require('../assets/videos/10.mp4'),
  '11': require('../assets/videos/11.mp4'),
  '9odem': require('../assets/videos/9odem.mp4'),
  'arjaa_ghodwa': require('../assets/videos/arjaa_ghodwa.mp4'),
  'asslema': require('../assets/videos/asslema.mp4'),
  'baladeya': require('../assets/videos/baladeya.mp4'),
  'chamel': require('../assets/videos/chamel.mp4'),
  'charaa': require('../assets/videos/charaa.mp4'),
  'chnoua_ismek': require('../assets/videos/chnoua_ismek.mp4'),
  'cv': require('../assets/videos/cv.mp4'),
  'dar': require('../assets/videos/dar.mp4'),
  'hmd': require('../assets/videos/hmd.mp4'),
  'janoub': require('../assets/videos/janoub.mp4'),
  'kadech_omrek': require('../assets/videos/kadech_omrek.mp4'),
  'labes': require('../assets/videos/labes.mp4'),
  'madhmoun': require('../assets/videos/madhmoun.mp4'),
  'madrasa': require('../assets/videos/madrasa.mp4'),
  'nabeul': require('../assets/videos/nabeul.mp4'),
  'sanna': require('../assets/videos/sanna.mp4'),
  'sfer': require('../assets/videos/sfer.mp4'),
  'takra': require('../assets/videos/takra.mp4'),
  'tekhdem': require('../assets/videos/tekhdem.mp4'),
  'win': require('../assets/videos/win.mp4'),
  'yamin': require('../assets/videos/yamin.mp4'),
  'ysar': require('../assets/videos/ysar.mp4'),
};

// Map of sign labels to their translations
export const signTranslations: { [key: string]: { arabic: string; french: string } } = {
  '1': { arabic: 'واحد', french: 'un' },
  '2': { arabic: 'اثنان', french: 'deux' },
  '3': { arabic: 'ثلاثة', french: 'trois' },
  '4': { arabic: 'أربعة', french: 'quatre' },
  '5': { arabic: 'خمسة', french: 'cinq' },
  '6': { arabic: 'ستة', french: 'six' },
  '7': { arabic: 'سبعة', french: 'sept' },
  '8': { arabic: 'ثمانية', french: 'huit' },
  '9': { arabic: 'تسعة', french: 'neuf' },
  '10': { arabic: 'عشرة', french: 'dix' },
  '11': { arabic: 'أحد عشر', french: 'onze' },
  '9odem': { arabic: 'قبل', french: 'avant' },
  'arjaa_ghodwa': { arabic: 'أرجع غدوة', french: 'reviens demain' },
  'asslema': { arabic: 'سلام', french: 'salut' },
  'baladeya': { arabic: 'بلدية', french: 'mairie' },
  'chamel': { arabic: 'شمال', french: 'nord' },
  'charaa': { arabic: 'شارع', french: 'rue' },
  'chnoua_ismek': { arabic: 'شنوا اسمك', french: 'quel est ton nom' },
  'cv': { arabic: 'سيرة ذاتية', french: 'cv' },
  'dar': { arabic: 'دار', french: 'maison' },
  'hmd': { arabic: 'حمد', french: 'louange' },
  'janoub': { arabic: 'جنوب', french: 'sud' },
  'kadech_omrek': { arabic: 'قداش عمرك', french: 'quel âge as-tu' },
  'labes': { arabic: 'لباس', french: 'vêtement' },
  'madhmoun': { arabic: 'مضمون', french: 'garanti' },
  'madrasa': { arabic: 'مدرسة', french: 'école' },
  'nabeul': { arabic: 'نابل', french: 'nabeul' },
  'sanna': { arabic: 'صنع', french: 'fabriqué' },
  'sfer': { arabic: 'سفر', french: 'voyage' },
  'takra': { arabic: 'تكرا', french: 'répète' },
  'tekhdem': { arabic: 'تخدم', french: 'tu travailles' },
  'win': { arabic: 'وين', french: 'où' },
  'yamin': { arabic: 'يمين', french: 'droite' },
  'ysar': { arabic: 'يسار', french: 'gauche' },
}; 